// Disable Tags: soldOut, notAvaliable

export const siteConfig = {
  title: "Course Catalog",
  subtitle: "A list of all STEM courses offered for students in grades K-12",
  scheduleImages: {
    "jan-april": {
      height: 700,
      width: 1300,
      alt: "Winter Course Schedule Overview",
      src: ""
    },
    holiday: {
      height: 700,
      width: 1300,
      alt: "Holiday Camp Schedule Overview",
      src: ""
    },
    fall: {
      height: 700,
      width: 1300,
      alt: "Fall Course Schedule Overview",
      src: "/gallery/schedule/fall2026.avif"
    },
    summer: {
      height: 700,
      width: 1300,
      alt: "Summer Program Schedule Overview",
      src: "/gallery/placeholder.webp"
    },
  },
}

export const janAprilConfig = {
  title: "2026 Winter Classes",
  description: "13 sessions from January 6 - April 13, 2025. Various STEM disciplines for Grades K-12.",
  classDates: {
    title: "Winter 2026 Class Dates:",
    schedule: {
      Tuesday: "Jan 7, 14, 21, 28 / Feb 4, 11, 18, 25 / Mar 4, 11, 18, 25 / Apr 1, 8",
      Thursday: "Jan 9, 16, 23, 30 / Feb 6, 13, 20, 27 / Mar 6, 13, 20, 27 / Apr 3, 10",
      Friday: "Jan 10, 17, 24, 31 / Feb 7, 14, 21, 28 / Mar 7, 14, 21, 28 / Apr 4, 11",
      Saturday: "Jan 11, 18, 25 / Feb 1, 8, 15, 22 / Mar 1, 8, 15, 22, 29 / Apr 5, 12",
      Sunday: "Jan 12, 19 / Feb 2, 9, 16 / Mar 2, 23, 30 / Apr 6, 13, 20",
    },
  },
}

export const holidayConfig = {
  title: "Holiday Camps",
  description:
    "Join us this holiday season for an immersive robotics and STEM experience. Campers will build and program their own robot, and create a custom holiday gift. All classes will be in-person in Bayside.",
  availableSessions: {
    title: "Available Sessions:",
    sessions: [
      "Session 1: Dec 26-28",
      "Session 2: Dec 30, Jan 2-3",
      "Session 3: February 20-22",
      "Session 4: April 17-19 or 18-20",
    ],
  },
}

export const fallConfig = {
  title: "2026 Fall Classes",
  description:
    "Robotics, programming, and game design for beginners to advanced levels. Special topics will run with enough students registered. 15 classes for the semester.",
  classDates: {
    title: "Class Dates",
    schedule: {
      Tuesday: "Sep 8, 15, 22, 29 / Oct 6, 13, 20, 27 / Nov 3, 10, 17, 24 / Dec 1, 8, 15",
      Wednesday: "Sep 9, 16, 23, 30 / Oct 7, 12, 21, 28 / Nov 4, 11, 18, 25 / Dec 1, 8, 15",
      Thursday: "Sep 10, 17, 24 / Oct 1, 8, 15, 22, 29 / Nov 5, 12, 19, 24* / Dec 3, 10, 17",
      Friday: "Sep 11, 18, 25 / Oct 2, 9, 16, 23, 30 / Nov 6, 13, 20, 23* / Dec 4, 11, 18",
      Saturday: "Sep 12, 19, 24 / Oct 3, 10, 17, 24, 31 / Nov 7, 14, 21 / Dec 5, 12, 19",
      Sunday: "Sep 13, 20, 27 / Oct 4, 11, 18, 25 / Nov 1, 8, 15, 22, 29 / Dec 6, 13, 20",
    },
  },
}

export const summerConfig = {
  title: "2026 Summer Programs",
  description: "Bootcamps, STEM camps, and weekend workshops covering robotics, electronics, and more.",
}

export const janAprilCourses = [
  {
    title: "Bayside Robotics for Grades K-3",
    description: "Introductory VEX IQ robotics for beginners with project-based learning.",
    gradeLevel: "K-3",
    dates: "Tuesday, Jan 8 - Mar 15",
    time: "Green - Tue/Thu/Sun",
    category: "Beginner Robotics",

    tags: ["robotics", "beginner", "vex-iq"],
    imageUrl: "/courses/vexiq.webp?height=200&width=300",
    skills: ["VEX IQ basics", "Robot development", "Block-based programming", "Problem-solving"],
    projects: ["VEX IQ Robot"],
  },
  {
    title: "RM002 - Robotics for Grades 5-8",
    description: "Intermediate VEX IQ robotics with advanced construction and programming.",
    gradeLevel: "5th - 8th Grade",
    dates: "Jan 6 - Apr 13, 2026",
    time: "Blue - Thursday only",
    category: "Intermediate Robotics",
    tags: ["robotics", "intermediate", "vex-iq"],
    imageUrl: "/courses/vexiq.webp?height=200&width=300",
    skills: ["Advanced VEX IQ", "Programming logic", "Sensors and tracking", "Model and Design"],
    projects: ["VEX IQ Robot"],
  },
  {
    title: "RV001 - Robotics for Grades 6-12",
    description: "VEX robotics covering gear ratios, torque, speed, and mechanical concepts.",
    gradeLevel: "6th - 12th Grade",
    dates: "Jan 6 - Apr 13, 2026",
    time: "Red - Sunday only",
    category: "Advanced Robotics",
    tags: ["robotics", "advanced", "vex", "competition"],
    imageUrl: "/courses/vex.webp?height=200&width=300",
    skills: ["VEX construction", "Gear ratios", "Torque calculations", "Programming"],
    projects: ["VEX Robot", "Launching platform"],
  },
  {
    title: "Battlebots 101",
    description: "Design and build battle bots from scratch with CAD and electronics.",
    gradeLevel: "6th - 12th Grade",
    dates: "Jan 6 - Apr 13, 2026",
    time: "Yellow - Friday only",
    category: "Engineering Design",
    tags: ["engineering", "design", "cad", "electronics"],
    imageUrl: "/courses/battlebot.webp?height=200&width=300",
    skills: ["Combat design", "CAD modeling", "Electronics", "Manufacturing"],
    projects: ["Battle Bot", "Control system", "Weapon prototypes",],
  },
  {
    title: "CTC001 - Programming for Grades K-5",
    description: "Learn programming fundamentals, data types, and C++ basics.",
    gradeLevel: "K - 5th Grade",
    dates: "Jan 6 - Apr 13, 2026",
    time: "Grey - Friday only",
    category: "Programming",
    tags: ["programming", "beginner", "cpp"],
    imageUrl: "/courses/programming.webp?height=200&width=300",
    skills: ["Programming logic", "Data types", "C++ basics", "Problem solving"],
    projects: ["Calculator"],
  },
  {
    title: "CPP002 - Programming for Grades 6-12",
    description: "Advanced programming with complex data types, loops, and I/O operations.",
    gradeLevel: "6th - 12th Grade",
    dates: "Jan 6 - Apr 13, 2026",
    time: "Orange - Friday only",
    category: "Advanced Programming",
    tags: ["programming", "advanced", "cpp"],
    imageUrl: "/courses/programming.webp?height=200&width=300",
    skills: ["Complex data types", "Loops", "I/O operations", "Functions"],
    projects: ["To-Do List", "Unit Converter"],
  },
  {
    title: "CPP003 - Programming for Grades 6-12",
    description: "Continuation of CPP002 with advanced concepts and data structures.",
    gradeLevel: "6th - 12th Grade",
    dates: "Jan 6 - Apr 13, 2026",
    time: "Orange - Saturday only",
    category: "Advanced Programming",
    tags: ["programming", "advanced", "cpp", "data-structures"],
    imageUrl: "/courses/programming.webp?height=200&width=300",
    skills: ["Data structures", "OOP", "Algorithms", "Software architecture"],
    projects: ["Note-Taking", "Expense Tracker"],
  },
  {
    title: "3D Modelling and Design",
    description: "Learn 3D modeling, additive/negative manufacturing, and design principles.",
    gradeLevel: "6th - 12th Grade",
    dates: "Jan 6 - Apr 13, 2026",
    time: "Purple - Thu/Sun",
    category: "Engineering Design",
    tags: ["design", "3d-modeling", "manufacturing"],
    imageUrl: "/courses/3dprinting.webp?height=200&width=300",
    skills: ["3D modeling", "Design principles", "Manufacturing", "Materials"],
    projects: ["Simple toys", "Geometric shapes"],
  },
]

export const holidayCourses = [
  {
    title: "Holiday Camp - Grades K-5 (Half Days)",
    description: "Design, build and program your own robot in this immersive 3-day experience.",
    gradeLevel: "K - 5th Grade",
    dates: "Multiple sessions available",
    time: "Morning 9am-12pm OR Afternoon 1pm-4pm",
    category: "Holiday Camp",
    tags: ["holiday", "robotics", "beginner", "half-day"],
    sessions: [
      { name: "Session 1", dates: "Dec 26-28", available: true },
      { name: "Session 2", dates: "Dec 30, Jan 2-3", available: true },
      { name: "Session 3", dates: "February 20-22", available: true },
      { name: "Session 4", dates: "April 17-19 or 18-20", available: true },
    ],
    imageUrl: "/courses/3dprinting2.webp?height=200&width=300",
    skills: ["Robot design", "Basic programming", "Problem solving", "Creative thinking"],
    projects: ["VEX IQ Custom robot", "Control systems", "Robot programming"],
  },
  {
    title: "Holiday Camp - Grades K-5 (Full Days)",
    description: "Design, build and program your own robot AND make a custom 3D printed holiday gift.",
    gradeLevel: "K - 5th Grade",
    dates: "Multiple sessions available",
    time: "Full days (extended hours)",
    category: "Holiday Camp",
    tags: ["holiday", "robotics", "3d-printing", "full-day"],
    sessions: [
      { name: "Session 1", dates: "Dec 26-28", available: true },
      { name: "Session 2", dates: "Dec 30, Jan 2-3", available: true },
      { name: "Session 3", dates: "February 20-22", available: true },
      { name: "Session 4", dates: "April 17-19 or 18-20", available: true },
    ],
    imageUrl: "/courses/3dprinting2.webp?height=200&width=300",
    skills: ["Robot design", "3D modeling", "Programming", "Gift design", "Manufacturing"],
    projects: ["VEX IQ Custom robot", "Control systems", "Custom holiday gift", "Robot programming"],
  },
  {
    title: "Holiday Camp - Grades 6-12 (Half Days)",
    description: "Advanced robotics camp where students design, build and program their own robot.",
    gradeLevel: "6th - 12th Grade",
    dates: "Multiple sessions available",
    time: "Morning 9am-12pm OR Afternoon 1pm-4pm",
    category: "Holiday Camp",
    tags: ["holiday", "robotics", "advanced", "half-day"],
    sessions: [
      { name: "Session 1", dates: "Dec 26-28", available: true },
      { name: "Session 2", dates: "Dec 30, Jan 2-3", available: true },
      { name: "Session 3", dates: "February 20-22", available: true },
      { name: "Session 4", dates: "April 17-19 or 18-20", available: true },
    ],
    imageUrl: "/courses/vexrobot.webp?height=200&width=300",
    skills: ["Advanced robotics", "Complex programming", "Engineering design", "System integration"],
    projects: ["VEX Custom robot", "Control systems", "Robot programming", "Presentations"],
  },
  {
    title: "Holiday Camp - Grades 6-12 (Full Days)",
    description: "Comprehensive camp combining advanced robotics with 3D printing to create custom holiday gifts.",
    gradeLevel: "6th - 12th Grade",
    dates: "Multiple sessions available",
    time: "Full days (extended hours)",
    category: "Holiday Camp",
    tags: ["holiday", "robotics", "3d-printing", "advanced", "full-day"],
    sessions: [
      { name: "Session 1", dates: "Dec 26-28", available: true },
      { name: "Session 2", dates: "Dec 30, Jan 2-3", available: true },
      { name: "Session 3", dates: "February 20-22", available: true },
      { name: "Session 4", dates: "April 17-19 or 18-20", available: true },
    ],
    imageUrl: "/courses/vexrobot.webp?height=200&width=300",
    skills: ["Advanced robotics", "3D CAD design", "Manufacturing", "Programming", "Project management"],
    projects: ["VEX Custom robot", "Control systems", "Custom holiday gift", "Robot programming", "Presentations"],
  },
]

//Fall Classes, Fall Courses, Fall Semester

export const fallCourses = [
  {
    title: "Robotics 100 for Grades K-3 (Tuesday, Bayside)",
    description: "Introductory VEX IQ robotics for youngest beginners with project-based learning.",
    gradeLevel: "K - 3rd Grade",
    dates: "15 classes",
    cost: "$100/class",
    time: "Tuesday 3:00pm-4:30pm",
    c2cLocation: "Bayside - 41-08 Bell Blvd, 2nd Floor",
    category: "Beginner",
    courseCode: "BRBT001-2303",
    color: "Light Blue",
    tags: ["robotics", "beginner", "vex-iq", "young-learners", "Bayside"],
    imageUrl: "/courses/vexiq1.webp?height=200&width=300",
    skills: ["VEX IQ basics",  "Block programming"],
    projects: ["VEX-IQ Robot", "Simple movements", "VEX-IQ platform"],
  },
  {
    title: "Robotics 100 for Grades 4-6 (Tuesday, Bayside)",
    description: "Introductory VEX IQ robotics for our youngest beginners with project-based learning.",
    gradeLevel: "4th - 6th Grade",
    dates: "15 classes",
    cost: "$100/class",
    c2cLocation: "Bayside - 41-08 Bell Blvd, 2nd Floor",
    time: "Tuesday 4:30pm-6:00pm",
    category: "Beginner",
    courseCode: "BRBT001-2446",
    color: "Light Blue",
    tags: ["robotics", "beginner", "vex-iq", "young-learners", "Bayside"],
    imageUrl: "/courses/vexiq1.webp?height=200&width=300",
    skills: ["VEX IQ basics",  "Structures", "Building", "Mechanics"],
    projects: ["VEX-IQ Robot", "Simple movements", "VEX-IQ platform"],
  },
  {
    title: "Robotics 100 for Grades 1-6 (Tuesday, Mineola)",
    description: "Introductory VEX IQ robotics for youngest beginners with project-based learning.",
    gradeLevel: "1st - 6th Grade",
    dates: "15 classes",
    cost: "$100/class",
    time: "Tuesday 4:00pm-5:30pm",
    c2cLocation: "Mineola - 254 E Jericho Turnpike",
    category: "Beginner",
    courseCode: "MRBT001-2416",
    color: "Light Blue",
    tags: ["robotics", "beginner", "vex-iq", "young-learners", "Mineola"],
    imageUrl: "/courses/vexiq1.webp?height=200&width=300",
    skills: ["VEX IQ basics",  "Block programming"],
    projects: ["VEX-IQ Robot", "Simple movements", "VEX-IQ platform"],
  },
  {
    title: "Robotics 101 for Grades K-3 (Tuesday, Bayside)",
    description: "Intermediate VEX IQ robotics to learn robotics programming and complex mechanisms.",
    gradeLevel: "K - 3rd Grade",
    dates: "15 classes",
    cost: "$100/class",
    c2cLocation: "Bayside - 41-08 Bell Blvd, 2nd Floor",
    time: "Tuesday 3:00pm-4:30pm",
    category: "Intermediate",
    courseCode: "BRBT101-2033",
    color: "Light Blue",
    tags: ["robotics", "intermediate", "vex-iq", "young-learners", "Bayside"],
    imageUrl: "/courses/competelevelup.webp?height=200&width=300",
    skills: ["VEX IQ basics", "Robot Development", "Structures", "Building", "Mechanics"],
    projects: ["VEX-IQ Robot", "Simple movements", "VEX-IQ platform"],
  },
  {
    title: "Robotics 101 for Grades 4-6 (Tuesday, Bayside)",
    description: "Intermediate VEX IQ robotics to learn robotics programming and complex mechanisms.",
    gradeLevel: "4th - 6th Grade",
    dates: "15 classes",
    cost: "$100/class",
    c2cLocation: "Bayside - 41-08 Bell Blvd, 2nd Floor",
    time: "Tuesday 4:30pm-6:00pm",
    category: "Intermediate",
    courseCode: "BRBT101-2446",
    color: "Light Blue",
    tags: ["robotics", "intermediate", "vex-iq", "young-learners", "Bayside"],
    imageUrl: "/courses/competelevelup.webp?height=200&width=300",
    skills: ["VEX IQ basics", "Robot Development", "Structures", "Building", "Mechanics"],
    projects: ["VEX-IQ Robot", "Simple movements", "VEX-IQ platform"],
  },
  {
    title: "Robotics 200 for Grades 7-12 (Tuesday, Bayside)",
    description: "Introduction to VEX robotics with gear ratios, torque, speed, and leverage concepts.",
    gradeLevel: "7th - 12th Grade",
    dates: "15 classes",
    cost: "$150/class",
    c2cLocation: "Bayside - 41-08 Bell Blvd, 2nd Floor",
    time: "Tuesday 6:00pm-7:30pm",
    category: "Beginner",
    courseCode: "BRBT200-2726",
    color: "Red",
    tags: ["robotics", "beginner", "vex", "v5", "engineering", "Bayside"],
    imageUrl: "/courses/vexrobot.webp?height=200&width=300",
    skills: ["VEX construction", "Gear ratios", "Torque concepts", "Speed calculations", "Leverage principles"],
    projects: ["Basic VEX robot", "Gear demonstrations", "Launching mechanism"],
  },
  {
    title: "Robotics 201 for Grades 7-12 (Tuesday, Bayside)",
    description: "Intermediate covering complex engineering concepts including CAD, dimensioning, DFM, and advanced mechanisms.",
    gradeLevel: "8th - 12th Grade",
    dates: "15 classes",
    cost: "$150/class",
    c2cLocation: "Bayside - 41-08 Bell Blvd, 2nd Floor",
    time: "Tuesday 6:00pm-7:30pm",
    category: "Intermediate",
    courseCode: "BRBT201-2726",
    color: "Red",
    tags: ["robotics", "intermediate", "vex", "v5", "high-school", "engineering", "Bayside"],
    imageUrl: "/courses/competeoverride.webp?height=200&width=300",
    skills: ["Advanced VEX systems", "Engineering principles", "Complex programming", "Competition design"],
    projects: ["VEX V5 Robot", "Advanced mechanisms", "Launching platform", "Robot navigation"],
  },
  {
    title: "Robotics 200 for Grades 7-12 (Tuesday, Mineola)",
    description: "Introduction to VEX robotics with gear ratios, torque, speed, and leverage concepts.",
    gradeLevel: "7th - 12th Grade",
    dates: "15 classes",
    cost: "$150/class",
    c2cLocation: "Mineola - 254 E Jericho Turnpike",
    time: "Tuesday 5:30pm-7:00pm",
    category: "Beginner",
    courseCode: "MRBT200-2725",
    color: "Red",
    tags: ["robotics", "beginner", "vex", "v5", "engineering", "Mineola"],
    imageUrl: "/courses/vexrobot.webp?height=200&width=300",
    skills: ["VEX construction", "Gear ratios", "Torque concepts", "Speed calculations", "Leverage principles"],
    projects: ["Basic VEX robot", "Gear demonstrations", "Launching mechanism"],
  },
  {
    title: "Robotics 100 for Grades K-3 (Thursday, Bayside)",
    description: "Introductory VEX IQ robotics for youngest beginners with project-based learning.",
    gradeLevel: "K - 3rd Grade",
    dates: "15 classes",
    cost: "$100/class",
    time: "Thursday 3:00pm-4:30pm",
    c2cLocation: "Bayside - 41-08 Bell Blvd, 2nd Floor",
    category: "Beginner",
    courseCode: "BRBT001-4033",
    color: "Light Blue",
    tags: ["robotics", "beginner", "vex-iq", "young-learners", "Bayside"],
    imageUrl: "/courses/vexiq1.webp?height=200&width=300",
    skills: ["VEX IQ basics",  "Block programming"],
    projects: ["VEX-IQ Robot", "Simple movements", "VEX-IQ platform"],
  },
  {
    title: "Robotics 100 for Grades 4-6 (Thursday, Bayside)",
    description: "Introductory VEX IQ robotics for our youngest beginners with project-based learning.",
    gradeLevel: "4th - 6th Grade",
    dates: "15 classes",
    cost: "$100/class",
    c2cLocation: "Bayside - 41-08 Bell Blvd, 2nd Floor",
    time: "Thursday 4:30pm-6:00pm",
    category: "Beginner",
    courseCode: "BRBT001-4446",
    color: "Light Blue",
    tags: ["robotics", "beginner", "vex-iq", "young-learners", "Bayside"],
    imageUrl: "/courses/vexiq1.webp?height=200&width=300",
    skills: ["VEX IQ basics",  "Structures", "Building", "Mechanics"],
    projects: ["VEX-IQ Robot", "Simple movements", "VEX-IQ platform"],
  },
  {
    title: "Robotics 100 for Grades 1-6 (Thursday, Mineola)",
    description: "Introductory VEX IQ robotics for youngest beginners with project-based learning.",
    gradeLevel: "1st - 6th Grade",
    dates: "15 classes",
    cost: "$100/class",
    time: "Thursday 4:00pm-5:30pm",
    c2cLocation: "Mineola - 254 E Jericho Turnpike",
    category: "Beginner",
    courseCode: "MRBT001-4416",
    color: "Light Blue",
    tags: ["robotics", "beginner", "vex-iq", "young-learners", "Mineola"],
    imageUrl: "/courses/vexiq1.webp?height=200&width=300",
    skills: ["VEX IQ basics",  "Block programming"],
    projects: ["VEX-IQ Robot", "Simple movements", "VEX-IQ platform"],
  },
  {
    title: "Robotics 200 for Grades 7-12 (Thursday, Mineola)",
    description: "Introduction to VEX robotics with gear ratios, torque, speed, and leverage concepts.",
    gradeLevel: "7th - 12th Grade",
    dates: "15 classes",
    cost: "$150/class",
    c2cLocation: "Mineola - 254 E Jericho Turnpike",
    time: "Thursday 5:30pm-7:00pm",
    category: "Beginner",
    courseCode: "MRBT200-4725",
    color: "Red",
    tags: ["robotics", "beginner", "vex", "v5", "engineering", "Mineola"],
    imageUrl: "/courses/vexrobot.webp?height=200&width=300",
    skills: ["VEX construction", "Gear ratios", "Torque concepts", "Speed calculations", "Leverage principles"],
    projects: ["Basic VEX robot", "Gear demonstrations", "Launching mechanism"],
  },
  {
    title: "Robotics 200 for Grades 7-12 (Sunday, Bayside)",
    description: "Introduction to VEX robotics with gear ratios, torque, speed, and leverage concepts.",
    gradeLevel: "7th - 12th Grade",
    dates: "15 classes",
    cost: "$150/class",
    c2cLocation: "Bayside - 41-08 Bell Blvd, 2nd Floor",
    time: "Sunday 1:00pm-2:30pm",
    category: "Beginner",
    courseCode: "BRBT200-7721",
    color: "Red",
    tags: ["robotics", "beginner", "vex", "v5", "engineering", "Bayside"],
    imageUrl: "/courses/vexrobot.webp?height=200&width=300",
    skills: ["VEX construction", "Gear ratios", "Torque concepts", "Speed calculations", "Leverage principles"],
    projects: ["Basic VEX robot", "Gear demonstrations", "Launching mechanism"],
  },
  {
    title: "Robotics 201 for Grades 7-12 (Sunday, Bayside)",
    description: "Intermediate covering complex engineering concepts including CAD, dimensioning, DFM, and advanced mechanisms.",
    gradeLevel: "7th - 12th Grade",
    dates: "15 classes",
    cost: "$150/class",
    c2cLocation: "Bayside - 41-08 Bell Blvd, 2nd Floor",
    time: "Sunday 1:00pm-2:30pm",
    category: "Intermediate",
    courseCode: "BRBT201-7721",
    color: "Red",
    tags: ["robotics", "intermediate", "vex", "v5", "high-school", "engineering", "Bayside"],
    imageUrl: "/courses/competeoverride.webp?height=200&width=300",
    skills: ["Advanced VEX systems", "Engineering principles", "CAD", "Complex programming", "Competition design"],
    projects: ["VEX V5 Robot", "Advanced mechanisms", "Launching platform", "Robot navigation"],
  },
  {
    title: "CTC001 - Programming for Grades K-5 (Friday, Bayside)",
    description: "Learn programming fundamentals of typing, computer related vocabulary, logic, syntax, data types, and C++ basics.",
    gradeLevel: "K - 5th Grade",
    dates: "15 classes",
    cost: "$100/class",
    c2cLocation: "Bayside - 41-08 Bell Blvd, 2nd Floor",
    time: "Friday, 3:30pm-5:00pm",
    category: "Programming",
    tags: ["programming", "beginner", "cpp", "Bayside"],
    imageUrl: "/courses/programming.webp?height=200&width=300",
    skills: ["Programming logic", "Data types", "C++ basics", "Problem solving"],
    projects: ["Calculator"],
  },
  {
    title: "CPP002 - Programming for Grades K-5 (Friday, Bayside)",
    description: "Intermediate programming with complex data types, loops, and I/O operations.",
    gradeLevel: "K - 5th Grade",
    dates: "15 classes",
    cost: "$100/class",
    c2cLocation: "Bayside - 41-08 Bell Blvd, 2nd Floor",    
    time: "Friday, 3:30pm-5:00pm",
    category: "Advanced Programming",
    tags: ["programming", "advanced", "cpp", "Bayside"],
    imageUrl: "/courses/programming.webp?height=200&width=300",
    skills: ["Complex data types", "Loops", "I/O operations", "Functions"],
    projects: ["To-Do List", "Unit Converter"],
  },
  {
    title: "CPP003 - Programming for Grades 6-12 (Friday, Bayside)",
    description: "Continuation of CPP002 with advanced concepts and data structures.",
    gradeLevel: "6th - 12th Grade",
    dates: "15 classes",
    cost: "$100/class",
    c2cLocation: "Bayside - 41-08 Bell Blvd, 2nd Floor",
    time: "Friday, 5:00pm-6:30pm",
    category: "Advanced Programming",
    tags: ["programming", "advanced", "cpp", "data-structures", "Bayside"],
    imageUrl: "/courses/programming.webp?height=200&width=300",
    skills: ["Data structures", "OOP", "Algorithms", "Software architecture"],
    projects: ["Note-Taking", "Expense Tracker"],
  },
  {
    title: "Special Topic: Design for Manufacturing 100 for Grades 6-12 (Thursday, Bayside)",
    description: "Learn 3D modeling, additive/negative manufacturing, and design principles.",
    gradeLevel: "6th - 12th Grade",
    dates: "15 classes",
    cost: "$150/class",
    c2cLocation: "Bayside - 41-08 Bell Blvd, 2nd Floor",
    time: "Thursday, 6:00pm-7:30pm",
    category: "Engineering Design",
    tags: ["design", "3d-modeling", "manufacturing", "Bayside"],
    imageUrl: "/courses/3dprinting.webp?height=200&width=300",
    skills: ["3D modeling", "Design principles", "Manufacturing", "Materials"],
    projects: ["Simple toys", "Geometric shapes"],
  },
  {
    title: "3D Digital Production 100 with Blender for Grades 6 - 12 (Tuesday, Mineola)",
    description: "Learn fundamentals of digital and graphic design including modelling, shaping, and more.",
    gradeLevel: "6th - 12th Grade",
    dates: "15 classes",
    cost: "$100/class",
    c2cLocation: "Mineola - 254 E Jericho Turnpike",
    time: "Tuesday, 4:00pm-5:30pm",
    category: "3D Digital Production",
    tags: ["3D modelling", "beginner", "blender", "Mineola"],
    imageUrl: "/courses/programming.webp?height=200&width=300",
    skills: ["3D modeling", "Design principles", "Manufacturing", "Materials"],
    projects: ["Calculator"],
  },
  {
    title: "3D Digital Production 100 with Blender for Grades 6 - 12 (Tuesday, Mineola)",
    description: "Learn fundamentals of digital and graphic design including modelling, shaping, and more.",
    gradeLevel: "6th - 12th Grade",
    dates: "15 classes",
    cost: "$100/class",
    c2cLocation: "Mineola - 254 E Jericho Turnpike",
    time: "Tuesday, 5:30pm-7:00pm",
    category: "3D Digital Production",
    tags: ["3D modelling", "beginner", "blender", "Mineola"],
    imageUrl: "/courses/programming.webp?height=200&width=300",
    skills: ["3D modeling", "Design principles", "Manufacturing", "Materials"],
    projects: ["Calculator"],
  },
  {
    title: "3D Digital Production 100 with Blender for Grades 6 - 12 (Wednesday, Bayside)",
    description: "Learn fundamentals of digital and graphic design including modelling, shaping, and more.",
    gradeLevel: "6th - 12th Grade",
    dates: "15 classes",
    cost: "$100/class",
    c2cLocation: "Bayside - 41-08 Bell Blvd, 2nd Floor",
    time: "Wednesday, 4:30pm-6:00pm",
    category: "3D Digital Production",
    tags: ["3D modelling", "beginner", "blender", "Bayside"],
    imageUrl: "/courses/programming.webp?height=200&width=300",
    skills: ["3D modeling", "Design principles", "Manufacturing", "Materials"],
    projects: ["Calculator"],
  },
  {
    title: "3D Digital Production 100 with Blender for Grades 6 - 12 (Wednesday, Bayside)",
    description: "Learn fundamentals of digital and graphic design including modelling, shaping, and more.",
    gradeLevel: "6th - 12th Grade",
    dates: "15 classes",
    cost: "$100/class",
    c2cLocation: "Bayside - 41-08 Bell Blvd, 2nd Floor",
    time: "Wednesday, 6:00pm-7:30pm",
    category: "3D Digital Production",
    tags: ["3D modelling", "beginner", "blender", "Bayside"],
    imageUrl: "/courses/programming.webp?height=200&width=300",
    skills: ["3D modeling", "Design principles", "Manufacturing", "Materials"],
    projects: ["Calculator"],
  },
   {
    title: "3D Digital Production 100 with Blender for Grades 6 - 12 (Sunday, Bayside)",
    description: "Learn fundamentals of digital and graphic design including modelling, shaping, and more.",
    gradeLevel: "6th - 12th Grade",
    dates: "15 classes",
    cost: "$100/class",
    c2cLocation: "Bayside - 41-08 Bell Blvd, 2nd Floor",
    time: "Sunday, 11:30am-1:00pm",
    category: "3D Digital Production",
    tags: ["3D modelling", "beginner", "blender", "Bayside"],
    imageUrl: "/courses/programming.webp?height=200&width=300",
    skills: ["3D modeling", "Design principles", "Manufacturing", "Materials"],
    projects: ["Calculator"],
  },
  {
    title: "AMC 8 Preparation",
    description: "Prepartion for American Math Competition 8 (AMC 8)",
    gradeLevel: "5 - 8th Grade",
    dates: "15 classes",
    cost: "$150/class",
    c2cLocation: "Bayside - 41-08 Bell Blvd, 2nd Floor",
    time: "Saturday, 10:00am-11:30am",
    category: "AMC8",
    tags: ["AMC8", "beginner", "math", "math competition", "Bayside"],
    imageUrl: "/courses/math.webp?height=200&width=300",
    skills: ["Logic", "Mathematics", "Math", "Problem solving"],
    projects: ["AMC8"],
  },
  {
    title: "AMC 8 Preparation",
    description: "Prepartion for American Math Competition 8 (AMC 8)",
    gradeLevel: "5 - 8th Grade",
    dates: "15 classes",
    cost: "$150/class",
    c2cLocation: "Bayside - 41-08 Bell Blvd, 2nd Floor",
    time: "Saturday, 3:00pm-4:30pm",
    category: "AMC8",
    tags: ["AMC8", "beginner", "math", "math competition", "Bayside"],
    imageUrl: "/courses/math.webp?height=200&width=300",
    skills: ["Logic", "Mathematics", "Math", "Problem solving"],
    projects: ["AMC8"],
  },
]

export const summerCourses = [
  {
    title: "Bayside VEX V5 Competition Bootcamp",
    description: "8-week intensive bootcamp for competition team preparation.",
    gradeLevel: "6th - 12th Grade",
    dates: "Jun 29 - Aug 21, 2026",
    
    time: "Mon/Wed/Fri Sessions, 9am-12pm OR 1pm-4pm",
    category: "Competition Bootcamp",
    tags: ["competition", "bootcamp", "vex-v5", "intensive", "Bayside"],
    imageUrl: "/courses/competeoverride.webp?height=200&width=300",
    skills: ["Programming", "Building and Designing", "Teamwork", "Public speaking"],
    projects: ["VEX V5 Robot", "Autonomous robot", "Drivetrain", "Lifting mechanisms"],
  },
  {
    title: "Bayside VEX IQ Competition Bootcamp",
    description: "8-week bootcamp for younger students interested in competition teams.",
    gradeLevel: "K - 8th Grade",
    dates: "Jun 29 - Aug 21, 2026",
    time: "Tue/Thu/Sat Sessions, 9am-12pm OR 1pm-4pm",
    category: "Competition Bootcamp",
    tags: ["competition", "bootcamp", "vex-iq", "intensive", "Bayside"],
    imageUrl: "/courses/competelevelup.webp?height=200&width=300",
    skills: ["Programming", "Building and Designing", "Teamwork", "Public speaking"],
    projects: ["VEX-IQ Robot", "Autonomous robot", "Drivetrain", "Lifting mechanisms"],
  },
  {
    title: "Mineola VEX V5 Competition Bootcamp",
    description: "8-week intensive bootcamp for competition team preparation.",
    gradeLevel: "6th - 12th Grade",
    dates: "July 6 - Aug 28, 2026",
    time: "Mon/Wed/Fri Sessions, 9am-12pm OR 1pm-4pm",
    category: "Competition Bootcamp",
    tags: ["competition", "bootcamp", "vex-v5", "intensive", "Mineola"],
    imageUrl: "/courses/competeoverride.webp?height=200&width=300",
    skills: ["Programming", "Building and Designing", "Teamwork", "Public speaking"],
    projects: ["VEX V5 Robot", "Autonomous robot", "Drivetrain", "Lifting mechanisms"],
  },
  {
    title: "Mineola VEX IQ Competition Bootcamp",
    description: "8-week bootcamp for younger students interested in competition teams.",
    gradeLevel: "K - 8th Grade",
    dates: "July 6 - Aug 28, 2026",
    time: "Mon/Wed/Fri Sessions, 9am-12pm OR 1pm-4pm",
    category: "Competition Bootcamp",
    tags: ["competition", "bootcamp", "vex-iq", "intensive", "Mineola"],
    imageUrl: "/courses/competelevelup.webp?height=200&width=300",
    skills: ["Programming", "Building and Designing", "Teamwork", "Public speaking"],
    projects: ["VEX-IQ Robot", "Autonomous robot", "Drivetrain", "Lifting mechanisms"],
  },
  {
    title: "Bayside Weekly Academic Camps",
    description: "Week-long camps covering math, English, Chinese, and STEAM including robotics, 3D printing, and more.",
    gradeLevel: "K - 12th Grade",
    dates: "Jun 29 - Aug 21, 2026",
    time: "Mon-Fri 9AM-4PM",
    category: "STEAM Camp",
    tags: ["stem", "camp", "3d-printing", "fabrication", "Bayside"],
    imageUrl: "/courses/vex.webp?height=200&width=300",
    skills: ["English", "Math", "Chinese", "Programming", "3D modeling", "Research methods"],
    projects: ["Presentations"],
  },
    {
    title: "Mineola Weekly Academic Camps",
    description: "Week-long camps covering math, English, Chinese, and STEAM including robotics, 3D printing, and more.",
    gradeLevel: "K - 12th Grade",
    dates: "July 6 - Aug 28, 2026",
    time: "Mon-Fri 9AM-4PM",
    category: "STEAM Camp",
    tags: ["stem", "camp", "3d-printing", "fabrication", "Mineola"],
    imageUrl: "/courses/vex.webp?height=200&width=300",
    skills: ["English", "Math", "Chinese", "Programming", "3D modeling", "Research methods"],
    projects: ["Presentations"],
  },
  {
    title: "Bayside Weekend Classes - Robotics Foundations",
    description: "Learn the basics of robotics.",
    gradeLevel: "K - 8th Grade",
    dates: "July 1 - Aug 29, 2026",
    time: "Sat 9AM-12PM",
    category: "Weekend Class",
    tags: ["weekend", "engineering", "robotics", "Bayside"],
    imageUrl: "/courses/battlebot.webp?height=200&width=300",
    skills: ["Programming", "Building and Designing", "Teamwork", "Public speaking"],
    projects: ["Robot design", "Control system"],
  },
  // {
  //   title: "Weekend Camps - Mini Battle Bots",
  //   description: "Design and build your own mini battle bot to take home.",
  //   gradeLevel: "4th - 12th Grade",
  //   dates: "Jul 12-13, 2025",
  //   time: "Sat/Sun 9AM-3PM",
  //   category: "Weekend Camp",
  //   tags: ["weekend", "battlebots", "engineering"],
  //   imageUrl: "/courses/battlebot.webp?height=200&width=300",
  //   skills: ["Combat design", "Electronics", "Safety protocols", "Strategy"],
  //   projects: ["Battle bot design", "Control system", "Take-home robot"],
  // },
  // {
  //   title: "Weekend Camps - Electronics",
  //   description: "Explore electronics fundamentals and create projects to take home.",
  //   gradeLevel: "4th - 12th Grade",
  //   dates: "Jul 19-20, 2025",
  //   time: "Sat/Sun 9AM-3PM",
  //   category: "Weekend Camp",
  //   tags: ["weekend", "electronics", "circuits"],
  //   soldOut: true,
  //   imageUrl: "/courses/ee.webp?height=200&width=300",
  //   skills: ["Circuit design", "Soldering", "Component ID", "Testing"],
  //   projects: ["LED controller", "Sound display", "Temperature monitor",],
  // },
  // {
  //   title: "Weekend Camps - Game Design",
  //   description: "Learn game development and create your own games.",
  //   gradeLevel: "4th - 12th Grade",
  //   dates: "Jul 26-27, 2025",
  //   time: "Sat/Sun 9AM-3PM",
  //   category: "Weekend Camp",
  //   tags: ["weekend", "game-design", "programming"],
  //   imageUrl: "/courses/tetris.webp?height=200&width=300",
  //   skills: ["Game design", "Programming", "UI design", "Animation"],
  //   projects: ["2D platform game", "Puzzle game"],
  // },
  // {
  //   title: "Weekend Camps - Drones",
  //   description: "Build and program your own drone with flight control systems.",
  //   gradeLevel: "4th - 12th Grade",
  //   dates: "Aug 9-10, 2025",
  //   time: "Sat/Sun 9AM-3PM",
  //   category: "Weekend Camp",
  //   tags: ["weekend", "drones", "flight", "programming"],
  //   imageUrl: "/courses/drone2.webp?height=200&width=300",
  //   skills: ["Aerodynamics", "Drone assembly", "Flight programming", "Safety"],
  //   projects: ["Flight patterns", "Obstacle navigation", "Take-home drone"],
  // },
  // {
  //   title: "Weekend Camps - Puzzle Making",
  //   description: "Design and create custom puzzles using engineering principles.",
  //   gradeLevel: "4th - 12th Grade",
  //   dates: "Aug 16-17, 2025",
  //   time: "Sat/Sun 9AM-3PM",
  //   category: "Weekend Camp",
  //   tags: ["weekend", "puzzles", "design", "3d-printing"],
  //   imageUrl: "/courses/puzzle.webp?height=200&width=300",
  //   skills: ["Puzzle design", "3D modeling", "Manufacturing", "UX design"],
  //   projects: ["Mechanical puzzle", "3D printed components", "Wooden puzzle"],
  // },
]
