// Disable Tags: soldOut, notAvaliable

export const siteConfig = {
  title: "Course Catalog",
  subtitle: "A list of all STEM courses offered for students in grades K-12",
  scheduleImages: {
    "jan-april": {
      height: 700,
      width: 1300,
      alt: "Winter Course Schedule Overview",
      //src: "/gallery/schedule/winter2025.avif"
    },
    holiday: {
      height: 700,
      width: 1300,
      alt: "Holiday Camp Schedule Overview",
      //src: "/gallery/placeholder.webp"
    },
    fall: {
      height: 700,
      width: 1300,
      alt: "Fall Course Schedule Overview",
      src: "/gallery/schedule/fall2026.avif"
    },
    summer: {
      height: 700,
      width: 1300,
      alt: "Summer Program Schedule Overview",
      src: "/gallery/placeholder.webp"
    },
  },
}

export const janAprilConfig = {
  title: "2026 Winter Classes",
  description: "13 sessions from January 6 - April 13, 2025. Various STEM disciplines for Grades K-12.",
  classDates: {
    title: "Winter 2026 Class Dates:",
    schedule: {
      Tuesday: "Jan 7, 14, 21, 28 / Feb 4, 11, 18, 25 / Mar 4, 11, 18, 25 / Apr 1, 8",
      Thursday: "Jan 9, 16, 23, 30 / Feb 6, 13, 20, 27 / Mar 6, 13, 20, 27 / Apr 3, 10",
      Friday: "Jan 10, 17, 24, 31 / Feb 7, 14, 21, 28 / Mar 7, 14, 21, 28 / Apr 4, 11",
      Saturday: "Jan 11, 18, 25 / Feb 1, 8, 15, 22 / Mar 1, 8, 15, 22, 29 / Apr 5, 12",
      Sunday: "Jan 12, 19 / Feb 2, 9, 16 / Mar 2, 23, 30 / Apr 6, 13, 20",
    },
  },
}

export const holidayConfig = {
  title: "Holiday Camps",
  description:
    "Join us this holiday season for an immersive robotics and STEM experience. Campers will build and program their own robot, and create a custom holiday gift. All classes will be in-person in Bayside.",
  availableSessions: {
    title: "Available Sessions:",
    sessions: [
      "Session 1: Dec 26-28",
      "Session 2: Dec 30, Jan 2-3",
      "Session 3: February 20-22",
      "Session 4: April 17-19 or 18-20",
    ],
  },
}

export const fallConfig = {
  title: "2025 Fall Classes",
  description:
    "Weekly robotics classes with 10 sessions per class. Introductory VEX IQ and VEX robotics courses for different grade levels.",
  classDates: {
    title: "Fall 2025 Class Dates:",
    schedule: {
      Tuesday: "Sep 9, 16, 23, 30 / Oct 7, 14, 21, 28 / Nov 4, 18",
      Thursday: "Sep 11, 18, 25 / Oct 2, 9, 16, 23, 30 / Nov 6, 13, 20",
      Friday: "Sep 12, 19, 26 / Oct 3, 10, 17, 24 / Nov 7, 14, 21",
      Saturday: "Sep 13, 20, 27 / Oct 4, 11, 18, 25 / Nov 8, 15, 22",
      Sunday: "Sep 14, 21, 28 / Oct 5, 12, 19, 26 / Nov 9, 16, 23",
    },
  },
}

export const summerConfig = {
  title: "2026 Summer Programs",
  description: "Bootcamps, STEM camps, and weekend workshops covering robotics, electronics, and more.",
}

export const janAprilCourses = [
  {
    title: "RM001 - Robotics for Grades K-5",
    description: "Introductory VEX IQ robotics for beginners with project-based learning.",
    gradeLevel: "K - 5th Grade",
    dates: "Jan 6 - Apr 13, 2026",
    time: "Green - Tue/Thu/Sun",
    category: "Beginner Robotics",

    tags: ["robotics", "beginner", "vex-iq"],
    imageUrl: "/courses/vexiq.webp?height=200&width=300",
    skills: ["VEX IQ basics", "Robot development", "Block-based programming", "Problem-solving"],
    projects: ["VEX IQ Robot"],
  },
  {
    title: "RM002 - Robotics for Grades 5-8",
    description: "Intermediate VEX IQ robotics with advanced construction and programming.",
    gradeLevel: "5th - 8th Grade",
    dates: "Jan 6 - Apr 13, 2026",
    time: "Blue - Thursday only",
    category: "Intermediate Robotics",
    tags: ["robotics", "intermediate", "vex-iq"],
    imageUrl: "/courses/vexiq.webp?height=200&width=300",
    skills: ["Advanced VEX IQ", "Programming logic", "Sensors and tracking", "Model and Design"],
    projects: ["VEX IQ Robot"],
  },
  {
    title: "RV001 - Robotics for Grades 6-12",
    description: "VEX robotics covering gear ratios, torque, speed, and mechanical concepts.",
    gradeLevel: "6th - 12th Grade",
    dates: "Jan 6 - Apr 13, 2026",
    time: "Red - Sunday only",
    category: "Advanced Robotics",
    tags: ["robotics", "advanced", "vex", "competition"],
    imageUrl: "/courses/vex.webp?height=200&width=300",
    skills: ["VEX construction", "Gear ratios", "Torque calculations", "Programming"],
    projects: ["VEX Robot", "Launching platform"],
  },
  {
    title: "Battlebots 101",
    description: "Design and build battle bots from scratch with CAD and electronics.",
    gradeLevel: "6th - 12th Grade",
    dates: "Jan 6 - Apr 13, 2026",
    time: "Yellow - Friday only",
    category: "Engineering Design",
    tags: ["engineering", "design", "cad", "electronics"],
    imageUrl: "/courses/battlebot.webp?height=200&width=300",
    skills: ["Combat design", "CAD modeling", "Electronics", "Manufacturing"],
    projects: ["Battle Bot", "Control system", "Weapon prototypes",],
  },
  {
    title: "CTC001 - Programming for Grades K-5",
    description: "Learn programming fundamentals, data types, and C++ basics.",
    gradeLevel: "K - 5th Grade",
    dates: "Jan 6 - Apr 13, 2026",
    time: "Grey - Friday only",
    category: "Programming",
    tags: ["programming", "beginner", "cpp"],
    imageUrl: "/courses/programming.webp?height=200&width=300",
    skills: ["Programming logic", "Data types", "C++ basics", "Problem solving"],
    projects: ["Calculator"],
  },
  {
    title: "CPP002 - Programming for Grades 6-12",
    description: "Advanced programming with complex data types, loops, and I/O operations.",
    gradeLevel: "6th - 12th Grade",
    dates: "Jan 6 - Apr 13, 2026",
    time: "Orange - Friday only",
    category: "Advanced Programming",
    tags: ["programming", "advanced", "cpp"],
    imageUrl: "/courses/programming.webp?height=200&width=300",
    skills: ["Complex data types", "Loops", "I/O operations", "Functions"],
    projects: ["To-Do List", "Unit Converter"],
  },
  {
    title: "CPP003 - Programming for Grades 6-12",
    description: "Continuation of CPP002 with advanced concepts and data structures.",
    gradeLevel: "6th - 12th Grade",
    dates: "Jan 6 - Apr 13, 2026",
    time: "Orange - Saturday only",
    category: "Advanced Programming",
    tags: ["programming", "advanced", "cpp", "data-structures"],
    imageUrl: "/courses/programming.webp?height=200&width=300",
    skills: ["Data structures", "OOP", "Algorithms", "Software architecture"],
    projects: ["Note-Taking", "Expense Tracker"],
  },
  {
    title: "3D Modelling and Design",
    description: "Learn 3D modeling, additive/negative manufacturing, and design principles.",
    gradeLevel: "6th - 12th Grade",
    dates: "Jan 6 - Apr 13, 2026",
    time: "Purple - Thu/Sun",
    category: "Engineering Design",
    tags: ["design", "3d-modeling", "manufacturing"],
    imageUrl: "/courses/3dprinting.webp?height=200&width=300",
    skills: ["3D modeling", "Design principles", "Manufacturing", "Materials"],
    projects: ["Simple toys", "Geometric shapes"],
  },
]

export const holidayCourses = [
  {
    title: "Holiday Camp - Grades K-5 (Half Days)",
    description: "Design, build and program your own robot in this immersive 3-day experience.",
    gradeLevel: "K - 5th Grade",
    dates: "Multiple sessions available",
    time: "Morning 9am-12pm OR Afternoon 1pm-4pm",
    category: "Holiday Camp",
    tags: ["holiday", "robotics", "beginner", "half-day"],
    sessions: [
      { name: "Session 1", dates: "Dec 26-28", available: true },
      { name: "Session 2", dates: "Dec 30, Jan 2-3", available: true },
      { name: "Session 3", dates: "February 20-22", available: true },
      { name: "Session 4", dates: "April 17-19 or 18-20", available: true },
    ],
    imageUrl: "/courses/3dprinting2.webp?height=200&width=300",
    skills: ["Robot design", "Basic programming", "Problem solving", "Creative thinking"],
    projects: ["VEX IQ Custom robot", "Control systems", "Robot programming"],
  },
  {
    title: "Holiday Camp - Grades K-5 (Full Days)",
    description: "Design, build and program your own robot AND make a custom 3D printed holiday gift.",
    gradeLevel: "K - 5th Grade",
    dates: "Multiple sessions available",
    time: "Full days (extended hours)",
    category: "Holiday Camp",
    tags: ["holiday", "robotics", "3d-printing", "full-day"],
    sessions: [
      { name: "Session 1", dates: "Dec 26-28", available: true },
      { name: "Session 2", dates: "Dec 30, Jan 2-3", available: true },
      { name: "Session 3", dates: "February 20-22", available: true },
      { name: "Session 4", dates: "April 17-19 or 18-20", available: true },
    ],
    imageUrl: "/courses/3dprinting2.webp?height=200&width=300",
    skills: ["Robot design", "3D modeling", "Programming", "Gift design", "Manufacturing"],
    projects: ["VEX IQ Custom robot", "Control systems", "Custom holiday gift", "Robot programming"],
  },
  {
    title: "Holiday Camp - Grades 6-12 (Half Days)",
    description: "Advanced robotics camp where students design, build and program their own robot.",
    gradeLevel: "6th - 12th Grade",
    dates: "Multiple sessions available",
    time: "Morning 9am-12pm OR Afternoon 1pm-4pm",
    category: "Holiday Camp",
    tags: ["holiday", "robotics", "advanced", "half-day"],
    sessions: [
      { name: "Session 1", dates: "Dec 26-28", available: true },
      { name: "Session 2", dates: "Dec 30, Jan 2-3", available: true },
      { name: "Session 3", dates: "February 20-22", available: true },
      { name: "Session 4", dates: "April 17-19 or 18-20", available: true },
    ],
    imageUrl: "/courses/vexrobot.webp?height=200&width=300",
    skills: ["Advanced robotics", "Complex programming", "Engineering design", "System integration"],
    projects: ["VEX Custom robot", "Control systems", "Robot programming", "Presentations"],
  },
  {
    title: "Holiday Camp - Grades 6-12 (Full Days)",
    description: "Comprehensive camp combining advanced robotics with 3D printing to create custom holiday gifts.",
    gradeLevel: "6th - 12th Grade",
    dates: "Multiple sessions available",
    time: "Full days (extended hours)",
    category: "Holiday Camp",
    tags: ["holiday", "robotics", "3d-printing", "advanced", "full-day"],
    sessions: [
      { name: "Session 1", dates: "Dec 26-28", available: true },
      { name: "Session 2", dates: "Dec 30, Jan 2-3", available: true },
      { name: "Session 3", dates: "February 20-22", available: true },
      { name: "Session 4", dates: "April 17-19 or 18-20", available: true },
    ],
    imageUrl: "/courses/vexrobot.webp?height=200&width=300",
    skills: ["Advanced robotics", "3D CAD design", "Manufacturing", "Programming", "Project management"],
    projects: ["VEX Custom robot", "Control systems", "Custom holiday gift", "Robot programming", "Presentations"],
  },
]

export const fallCourses = [
  {
    title: "RBT001 - Robotics 100 (Grades K-3)",
    description: "Introductory VEX IQ robotics for youngest beginners with project-based learning.",
    gradeLevel: "K - 3rd Grade",
    dates: "10 sessions - Fall 2025",
    time: "Tuesday 3:00pm-4:00pm OR Sunday 9:00am-10:00am",
    category: "Beginner Robotics",
    courseCode: "RBT001",
    color: "Light Blue",
    tags: ["robotics", "beginner", "vex-iq", "young-learners"],
    imageUrl: "/courses/vexiq1.webp?height=200&width=300",
    skills: ["VEX IQ basics",  "Block programming"],
    projects: ["VEX-IQ Robot", "Simple movements", "VEX-IQ platform"],
  },
  {
    title: "RBT001 - Robotics 100 (Grades 4-6)",
    description: "Introductory VEX IQ robotics with more complex projects for elementary students.",
    gradeLevel: "4th - 6th Grade",
    dates: "10 sessions - Fall 2025",
    time: "Tuesday 4:00pm-5:30pm OR Saturday 12:00pm-1:30pm",
    category: "Beginner Robotics",
    courseCode: "RBT001",
    color: "Light Blue",
    tags: ["robotics", "beginner", "vex-iq", "elementary"],
    imageUrl: "/courses/vexiq1.webp?height=200&width=300",
    skills: ["VEX IQ basics", "Robot development", "Block-based programming", "Problem-solving"],
    projects: ["VEX IQ Robot"],
  },
  {
    title: "RBT001 - Robotics 100 (Grades 6-8)",
    description: "Advanced VEX IQ robotics for middle school students with complex mechanisms.",
    gradeLevel: "6th - 8th Grade",
    dates: "10 sessions - Fall 2025",
    time: "Saturday 6:00pm-7:00pm",
    category: "Intermediate Robotics",
    courseCode: "RBT001",
    color: "Light Blue",
    tags: ["robotics", "intermediate", "vex-iq", "middle-school"],
    imageUrl: "/courses/vexiq.webp?height=200&width=300",
    skills: ["VEX IQ basics", "Robot development", "Block-based programming", "Problem-solving"],
    projects: ["VEX-IQ robots", "Advanced mechanisms", "Motion and sensors"],
  },
  {
    title: "RBT002 - Robotics 200 (Grades 6-8)",
    description: "Introduction to VEX robotics with gear ratios, torque, speed, and leverage concepts.",
    gradeLevel: "6th - 8th Grade",
    dates: "10 sessions - Fall 2025",
    time: "Tuesday 6:00pm-7:30pm",
    category: "Advanced Robotics",
    courseCode: "RBT002",
    color: "Red",
    tags: ["robotics", "advanced", "vex", "engineering"],
    imageUrl: "/courses/vexiq.webp?height=200&width=300",
    skills: ["VEX construction", "Gear ratios", "Torque concepts", "Speed calculations", "Leverage principles"],
    projects: ["Basic VEX robot", "Gear demonstrations", "Launching mechanism"],
  },
  {
    title: "RBT002 - Robotics 200 (Grades 8-12)",
    description: "Advanced VEX robotics covering complex engineering concepts for high school students.",
    gradeLevel: "8th - 12th Grade",
    dates: "10 sessions - Fall 2025",
    time: "Tuesday 7:30pm-9:00pm OR Saturday 7:30pm-9:00pm OR Sunday 10:30am-12:00pm",
    category: "Advanced Robotics",
    courseCode: "RBT002",
    color: "Red",
    tags: ["robotics", "advanced", "vex", "high-school", "engineering"],
    imageUrl: "/courses/vex.webp?height=200&width=300",
    skills: ["Advanced VEX systems", "Engineering principles", "Complex programming", "Competition design"],
    projects: ["VEX V5 Robot", "Advanced mechanisms", "Launching platform", "Robot navigation"],
  },
]

export const summerCourses = [
  {
    title: "VEX V5 Competition Bootcamp",
    description: "8-week intensive bootcamp for competition team preparation.",
    gradeLevel: "6th - 12th Grade",
    dates: "Jun 29 - Aug 28, 2026",
    
    time: "Tue/Thu/Fri Sessions",
    category: "Competition Bootcamp",
    tags: ["competition", "bootcamp", "vex-v5", "intensive"],
    imageUrl: "/courses/competeoverride.webp?height=200&width=300",
    skills: ["Programming", "Building and Designing", "Teamwork", "Public speaking"],
    projects: ["VEX V5 Robot", "Autonomous robot", "Drivetrain", "Lifting mechanisms"],
  },
  {
    title: "VEX IQ Competition Bootcamp",
    description: "8-week bootcamp for younger students interested in competition teams.",
    gradeLevel: "K - 8th Grade",
    dates: "Jun 29 - Aug 28, 2026",
    time: "Tue/Thu/Sat Sessions",
    category: "Competition Bootcamp",
    tags: ["competition", "bootcamp", "vex-iq", "intensive"],
    imageUrl: "/courses/competelevelup.webp?height=200&width=300",
    skills: ["Programming", "Building and Designing", "Teamwork", "Public speaking"],
    projects: ["VEX-IQ Robot", "Autonomous robot", "Drivetrain", "Lifting mechanisms"],
  },
  {
    title: "Weekly Academic Camps",
    description: "Week-long camps covering math, English, Chinese, and STEAM including robotics, 3D printing, and more.",
    gradeLevel: "K - 12th Grade",
    dates: "Jun 29 - Aug 28, 2026",
    time: "Mon-Fri 9AM-4PM",
    category: "STEM Camp",
    tags: ["stem", "camp", "3d-printing", "fabrication"],
    imageUrl: "/courses/vex.webp?height=200&width=300",
    skills: ["English", "Math", "Chinese", "Programming", "3D modeling", "Research methods"],
    projects: ["Presentations"],
  },
  {
    title: "Weekend Classes - Robotics Foundations",
    description: "Learn the basics of robotics.",
    gradeLevel: "K - 8th Grade",
    dates: "July 11-Aug 29, 2026",
    time: "Sat 9AM-12PM",
    category: "Weekend Camp",
    tags: ["weekend", "engineering", "robotics"],
    imageUrl: "/courses/battlebot.webp?height=200&width=300",
    skills: ["Programming", "Building and Designing", "Teamwork", "Public speaking"],
    projects: ["Robot design", "Control system"],
  },
  // {
  //   title: "Weekend Camps - Mini Battle Bots",
  //   description: "Design and build your own mini battle bot to take home.",
  //   gradeLevel: "4th - 12th Grade",
  //   dates: "Jul 12-13, 2025",
  //   time: "Sat/Sun 9AM-3PM",
  //   category: "Weekend Camp",
  //   tags: ["weekend", "battlebots", "engineering"],
  //   imageUrl: "/courses/battlebot.webp?height=200&width=300",
  //   skills: ["Combat design", "Electronics", "Safety protocols", "Strategy"],
  //   projects: ["Battle bot design", "Control system", "Take-home robot"],
  // },
  // {
  //   title: "Weekend Camps - Electronics",
  //   description: "Explore electronics fundamentals and create projects to take home.",
  //   gradeLevel: "4th - 12th Grade",
  //   dates: "Jul 19-20, 2025",
  //   time: "Sat/Sun 9AM-3PM",
  //   category: "Weekend Camp",
  //   tags: ["weekend", "electronics", "circuits"],
  //   soldOut: true,
  //   imageUrl: "/courses/ee.webp?height=200&width=300",
  //   skills: ["Circuit design", "Soldering", "Component ID", "Testing"],
  //   projects: ["LED controller", "Sound display", "Temperature monitor",],
  // },
  // {
  //   title: "Weekend Camps - Game Design",
  //   description: "Learn game development and create your own games.",
  //   gradeLevel: "4th - 12th Grade",
  //   dates: "Jul 26-27, 2025",
  //   time: "Sat/Sun 9AM-3PM",
  //   category: "Weekend Camp",
  //   tags: ["weekend", "game-design", "programming"],
  //   imageUrl: "/courses/tetris.webp?height=200&width=300",
  //   skills: ["Game design", "Programming", "UI design", "Animation"],
  //   projects: ["2D platform game", "Puzzle game"],
  // },
  // {
  //   title: "Weekend Camps - Drones",
  //   description: "Build and program your own drone with flight control systems.",
  //   gradeLevel: "4th - 12th Grade",
  //   dates: "Aug 9-10, 2025",
  //   time: "Sat/Sun 9AM-3PM",
  //   category: "Weekend Camp",
  //   tags: ["weekend", "drones", "flight", "programming"],
  //   imageUrl: "/courses/drone2.webp?height=200&width=300",
  //   skills: ["Aerodynamics", "Drone assembly", "Flight programming", "Safety"],
  //   projects: ["Flight patterns", "Obstacle navigation", "Take-home drone"],
  // },
  // {
  //   title: "Weekend Camps - Puzzle Making",
  //   description: "Design and create custom puzzles using engineering principles.",
  //   gradeLevel: "4th - 12th Grade",
  //   dates: "Aug 16-17, 2025",
  //   time: "Sat/Sun 9AM-3PM",
  //   category: "Weekend Camp",
  //   tags: ["weekend", "puzzles", "design", "3d-printing"],
  //   imageUrl: "/courses/puzzle.webp?height=200&width=300",
  //   skills: ["Puzzle design", "3D modeling", "Manufacturing", "UX design"],
  //   projects: ["Mechanical puzzle", "3D printed components", "Wooden puzzle"],
  // },
]
